"""Per-run feature dictionary — the companion CSV to result.csv.

Downstream analyses label tables and figures with the exposure column names
(`LILATracts_1And10`, `dist_pri`, ...), which nobody outside this project can
read. This writes a dictionary alongside each run's result.csv:

    feature_name,short_description,detailed_description

Written at merge time rather than served on demand, so it is archived with the
run it describes: the dictionary always lists exactly the columns that run
produced, even after the catalog gains or renames variables.

Source of truth is app/data/feature_dictionary.json, generated by
scripts/extend_ontology.py from the same table that authors the ontology's
value_col nodes — one place to edit, two artifacts.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

_DICT_PATH = Path(__file__).resolve().parent / "data" / "feature_dictionary.json"
FIELDNAMES = ("feature_name", "short_description", "detailed_description")


def _features() -> dict[str, dict]:
    return json.loads(_DICT_PATH.read_text())["features"]


def rows_for(columns: list[str]) -> list[dict[str, str]]:
    """Dictionary rows for `columns`, in the order given.

    Columns with no entry are skipped rather than emitted blank: the caller
    passes result.csv's full header, which includes the cohort's own columns
    (pid, dates, coordinates, any geography the user supplied) — those are
    inputs the user already understands, not linked features.
    """
    features = _features()
    return [
        {
            "feature_name": col,
            "short_description": features[col]["label"],
            "detailed_description": features[col]["definition"],
        }
        for col in columns
        if col in features
    ]


def write_csv(columns: list[str], out_path: Path) -> Path:
    """Write the dictionary for `columns`. Always writes a header, even when
    no column matched, so downstream code can read the file unconditionally."""
    rows = rows_for(columns)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    return out_path
